Repository redBorder/cookbook-rb-ips, pull requests merged in 2023-12, with the labels that each got.

#6 add rb-selinux
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/XS

#7 Add cgroup cookbook and trigger configure
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/XS, kind/feature

#9 release 0.1.4
  packaging/rpm/cookbook-rb-ips.spec
  resources/metadata.rb
Labels: size/XS, kind/documentation
