Repository redBorder/cookbook-rb-ips, pull requests merged in 2024-04, with the labels that each got.

#15 Release 0.1.8
  resources/metadata.rb
Labels: size/XS, kind/documentation

#13 Add country.dat file
  resources/files/default/country.dat
  resources/recipes/configure.rb
Labels: size/XS, kind/documentation

#16 Release 0.1.9
  CHANGELOG.md
  resources/metadata.rb
Labels: size/S, kind/documentation, release

#19 CI/CD
  .github/workflows/rpm.yml
Labels: kind/feature, size/M
