Repository redBorder/cookbook-rb-ips, pull requests merged in 2024-06, with the labels that each got.

#30 add temporary variables in node.run_state
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/XS, kind/feature

#31 Release 0.3.1
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/M, kind/documentation

#32 Release 0.3.2
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: bug, size/XS, release

#33 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/get_groups_in_use_info.rb
  resources/libraries/get_namespaces.rb
  resources/libraries/get_orgs.rb
  resources/libraries/get_sensors_all_info.rb
  resources/libraries/get_sensors_info.rb
  resources/libraries/in_hash.rb
  resources/libraries/ips_services.rb
  resources/libraries/memory_services.rb
  resources/libraries/util.rb
  resources/recipes/configure.rb
  resources/recipes/configure_cron_tasks.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/recipes/prepare_system.rb
  resources/recipes/system_health.rb
  resources/templates/default/sysconfig_chef-client.rb.erb
Labels: enhancement, kind/bug, lint, refactor

#34 Release 0.3.3
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/get_groups_in_use_info.rb
  resources/libraries/get_namespaces.rb
  resources/libraries/get_orgs.rb
  resources/libraries/get_sensors_all_info.rb
  resources/libraries/get_sensors_info.rb
  resources/libraries/in_hash.rb
  resources/libraries/ips_services.rb
  resources/libraries/memory_services.rb
  resources/libraries/util.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/configure_cron_tasks.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/recipes/prepare_system.rb
  resources/recipes/system_health.rb
  resources/templates/default/sysconfig_chef-client.rb.erb
Labels: kind/documentation

#35 add exporter service
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/feature

#36 Add clamAV
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/XS, kind/feature

#37 Release 0.4.0
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation
