Repository redBorder/cookbook-rb-ips, pull requests merged in 2024-01, with the labels that each got.

#8 Add configure_journald
  resources/recipes/configure.rb
  resources/recipes/configure_cron_tasks.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/systemd-journald_journald.conf.erb
Labels: kind/feature, size/M

#10 Release 0.1.5
  packaging/rpm/cookbook-rb-ips.spec
  resources/metadata.rb
Labels: size/XS, kind/documentation

#11 configure redborder monitor
  resources/recipes/configure.rb
Labels: size/XS, kind/feature
