Repository redBorder/cookbook-rb-ips, pull requests merged in 2024-05, with the labels that each got.

#21 excluding chef-client
  resources/attributes/default.rb
  resources/libraries/memory_services.rb
  resources/recipes/prepare_system.rb
Labels: bug, kind/feature, size/M

#22 Release 0.1.10
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/memory_services.rb
  resources/metadata.rb
  resources/recipes/prepare_system.rb
Labels: size/M, kind/documentation

#23 Call rb_get_sensor_rules_cloud.rb using rvm
  resources/recipes/configure.rb
Labels: bug, size/XS, kind/bug

#24 Release 0.1.11
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation

#25 Add configure common cookbook call
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/XS, kind/feature, feature

#26 Release 0.2.0
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation

#28 Add full kernel release info in motd
  resources/templates/default/motd.erb
Labels: size/XS, kind/documentation
